imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*, 3pp/*, src/*, app/src/Source/*, webroot/css/anax-grid/lessphp/*]

tools:
    external_code_coverage:
        timeout: 600 # Timeout in seconds.
